/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "minifyjpeg.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 120, 0 };

enum clnt_stat 
minify_jpeg_proc_1(JPEG_IN arg1, JPEG_OUT *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, MINIFY_JPEG_PROC,
		(xdrproc_t) xdr_JPEG_IN, (caddr_t) &arg1,
		(xdrproc_t) xdr_JPEG_OUT, (caddr_t) clnt_res,
		TIMEOUT));
}
